CREATE TABLE lessons
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lesson_name  VARCHAR(255)                            NOT NULL,
    duration     INT,
    content_type VARCHAR(255),
    status       VARCHAR(255),
    course_code  VARCHAR(255),
    start_date   date,
    CONSTRAINT pk_lessons PRIMARY KEY (id)
);

ALTER TABLE lessons
    ADD CONSTRAINT FK_LESSONS_ON_COCOSTDA FOREIGN KEY (course_code, start_date) REFERENCES courses (course_code, start_date);