CREATE TABLE course
(
    id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                         NOT NULL,
    credit INT                                  NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id)
);
CREATE TABLE course
(
    id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                         NOT NULL,
    credit INT                                  NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id)
);
CREATE TABLE course
(
    id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                         NOT NULL,
    credit INT                                  NOT NULL,
    CONSTRAINT pk_course PRIMARY KEY (id)
);