CREATE TABLE IF NOT EXISTS cinema_room
(
    room_id        INT AUTO_INCREMENT NOT NULL,
    room_name      VARCHAR(100)       NOT NULL,
    room_detail_id INT                NULL,
    CONSTRAINT pk_cinema_room PRIMARY KEY (room_id)
);

ALTER TABLE cinema_room
    ADD CONSTRAINT uc_cinema_room_room_detail UNIQUE (room_detail_id);

ALTER TABLE cinema_room
    ADD CONSTRAINT FK_CINEMA_ROOM_ON_ROOM_DETAIL FOREIGN KEY (room_detail_id) REFERENCES cinema_room_detail (room_detail_id);
CREATE TABLE cinema_room
(
    room_id        INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    room_name      VARCHAR(100)                         NOT NULL,
    room_detail_id INT,
    CONSTRAINT pk_cinema_room PRIMARY KEY (room_id)
);

ALTER TABLE cinema_room
    ADD CONSTRAINT uc_cinema_room_room_detail UNIQUE (room_detail_id);

ALTER TABLE cinema_room
    ADD CONSTRAINT FK_CINEMA_ROOM_ON_ROOM_DETAIL FOREIGN KEY (room_detail_id) REFERENCES cinema_room_detail (room_detail_id);