CREATE TABLE seat
(
    seat_id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    seat_row    INT                                  NOT NULL,
    seat_column INT                                  NOT NULL,
    seat_status VARCHAR(20)                          NOT NULL,
    seat_type   VARCHAR(20)                          NOT NULL,
    room_id     INT                                  NOT NULL,
    CONSTRAINT pk_seat PRIMARY KEY (seat_id)
);

ALTER TABLE seat
    ADD CONSTRAINT FK_SEAT_ON_ROOM FOREIGN KEY (room_id) REFERENCES cinema_room (room_id);