# H2 Database Connection Properties
db.driver=org.h2.Driver
db.url=jdbc:h2:./db/fadb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
db.username=sa
db.password=
db.dialect=org.hibernate.dialect.H2Dialect
db.hbm2ddl.auto=update
db.show_sql=true
db.format_sql=true
