# C?u hình chu?i k?t n?i H2 ch?y trên RAM
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# B?t giao di?n qu?n lý H2 Console trên trình duy?t
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# T? ??ng t?o c?u trúc b?ng t? các class @Entity c?a b?n
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
