# Spring Boot Configuration
server.port=8082

# Multipart configuration (limits file size for uploads)
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Thymeleaf caching disabled for easy development
spring.thymeleaf.cache=false
