spring.application.name=Ex2

spring.datasource.url=jdbc:postgresql://localhost:5432/menudb
spring.datasource.username=postgres
spring.datasource.password=160803

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true