CREATE TABLE assessment_materials
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title       VARCHAR(255),
    description VARCHAR(255),
    file_name   VARCHAR(255),
    CONSTRAINT pk_assessment_materials PRIMARY KEY (id)
);