CREATE TABLE courses
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title            VARCHAR(255),
    instructor_name  VARCHAR(255),
    instructor_email VARCHAR(255),
    description      VARCHAR(200),
    duration_hours   INT                                     NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);