# Server Port
server.port=8080

# Application Name
spring.application.name=trainingrest

# Database Configuration (H2 in-memory database)
spring.datasource.url=jdbc:h2:mem:trainingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA and Hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console Settings
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Swagger OpenAPI Path Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT Configuration Details
# 256-bit HS256 Signing Secret Key
app.jwt.secret=9a7561a35c5c4cb8aa789f2bf05cf25ef14ffc186bfbf7faeb94819d9b68e98031201083
# 1 Hour Access Token Expiration (3600000 ms)
app.jwt.expiration-milliseconds=3600000
# 24 Hours Refresh Token Expiration (86400000 ms)
app.jwt.refresh-expiration-milliseconds=86400000
