# Tên ứng dụng Spring Boot
spring.application.name=Ex1

# Cổng chạy ứng dụng Web Server
server.port=8080

# Cấu hình Kết nối CSDL PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/LMS
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# Cấu hình Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tắt cache của Thymeleaf khi phát triển
spring.thymeleaf.cache=false
