# Global log level
org.slf4j.simpleLogger.defaultLogLevel=error

# Show Hibernate SQL
org.slf4j.simpleLogger.log.org.hibernate.SQL=debug

# Hide Hibernate internal logs
org.slf4j.simpleLogger.log.org.hibernate=error
org.slf4j.simpleLogger.log.org.hibernate.orm.connections.pooling=error
org.slf4j.simpleLogger.log.org.hibernate.type.descriptor.sql=error

# Optional formatting
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false