# ===========================
# Application Configuration
# ===========================
server.port=8081
spring.application.name=User Security Management System

# ===========================
# PostgreSQL DataSource
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/Ex3_Security
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
# JPA / Hibernate
# ===========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===========================
# Thymeleaf
# ===========================
spring.thymeleaf.cache=false

# ===========================
# SQL Initialization
# ===========================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
