CREATE TABLE courses
(
    id     INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(255)                         NOT NULL,
    credit INT                                  NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);