CREATE TABLE courses
(
    course_code VARCHAR(255) NOT NULL,
    start_date  DATE         NOT NULL,
    course_name VARCHAR(255) NOT NULL,
    category    VARCHAR(255),
    instructor  VARCHAR(255),
    CONSTRAINT pk_courses PRIMARY KEY (course_code, start_date)
);

CREATE TABLE lessons
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lesson_name  VARCHAR(255)                            NOT NULL,
    duration     INTEGER,
    content_type VARCHAR(255),
    status       VARCHAR(255),
    course_code  VARCHAR(255)                            NOT NULL,
    start_date   DATE                                    NOT NULL,
    CONSTRAINT pk_lessons PRIMARY KEY (id)
);

ALTER TABLE lessons
    ADD CONSTRAINT fk_lessons_on_courses FOREIGN KEY (course_code, start_date) 
    REFERENCES courses (course_code, start_date)
    ON DELETE CASCADE;
