CREATE TABLE student_course
(
    course_id  INT NOT NULL,
    student_id INT NOT NULL,
    CONSTRAINT pk_student_course PRIMARY KEY (course_id, student_id)
);

CREATE TABLE students
(
    id   INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                         NOT NULL,
    age  INT                                  NOT NULL,
    CONSTRAINT pk_students PRIMARY KEY (id)
);

ALTER TABLE student_course
    ADD CONSTRAINT fk_stucou_on_course FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE student_course
    ADD CONSTRAINT fk_stucou_on_student FOREIGN KEY (student_id) REFERENCES students (id);